# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'config_editor.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QLineEdit,
    QListView, QMainWindow, QPushButton, QSizePolicy,
    QSlider, QSpinBox, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(610, 570)
        MainWindow.setMinimumSize(QSize(610, 570))
        MainWindow.setMaximumSize(QSize(610, 570))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 20, 49, 16))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.nameInput = QLineEdit(self.centralwidget)
        self.nameInput.setObjectName(u"nameInput")
        self.nameInput.setGeometry(QRect(230, 40, 371, 22))
        self.nameInput.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(230, 70, 49, 16))
        self.label_2.setFont(font)
        self.urlInput = QLineEdit(self.centralwidget)
        self.urlInput.setObjectName(u"urlInput")
        self.urlInput.setGeometry(QRect(230, 90, 371, 22))
        self.urlInput.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(230, 130, 16, 21))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(420, 130, 16, 21))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(230, 210, 71, 21))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(420, 210, 121, 21))
        self.label_6.setFont(font)
        self.cropBottomInput = QSpinBox(self.centralwidget)
        self.cropBottomInput.setObjectName(u"cropBottomInput")
        self.cropBottomInput.setGeometry(QRect(520, 210, 81, 24))
        self.xInput = QSpinBox(self.centralwidget)
        self.xInput.setObjectName(u"xInput")
        self.xInput.setGeometry(QRect(330, 130, 81, 24))
        self.yInput = QSpinBox(self.centralwidget)
        self.yInput.setObjectName(u"yInput")
        self.yInput.setGeometry(QRect(520, 130, 81, 24))
        self.cropRightInput = QSpinBox(self.centralwidget)
        self.cropRightInput.setObjectName(u"cropRightInput")
        self.cropRightInput.setGeometry(QRect(520, 240, 81, 24))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 240, 71, 21))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(420, 240, 121, 21))
        self.label_8.setFont(font)
        self.heightInput = QSpinBox(self.centralwidget)
        self.heightInput.setObjectName(u"heightInput")
        self.heightInput.setGeometry(QRect(520, 170, 81, 24))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(230, 170, 51, 21))
        self.label_9.setFont(font)
        self.widthInput = QSpinBox(self.centralwidget)
        self.widthInput.setObjectName(u"widthInput")
        self.widthInput.setGeometry(QRect(330, 170, 81, 24))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(420, 170, 51, 21))
        self.label_10.setFont(font)
        self.opacitySlider = QSlider(self.centralwidget)
        self.opacitySlider.setObjectName(u"opacitySlider")
        self.opacitySlider.setGeometry(QRect(299, 280, 301, 22))
        font1 = QFont()
        font1.setPointSize(11)
        self.opacitySlider.setFont(font1)
        self.opacitySlider.setMaximum(100)
        self.opacitySlider.setValue(100)
        self.opacitySlider.setOrientation(Qt.Orientation.Horizontal)
        self.opacitySlider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(230, 280, 71, 21))
        self.label_11.setFont(font)
        self.frameCheckBox = QCheckBox(self.centralwidget)
        self.frameCheckBox.setObjectName(u"frameCheckBox")
        self.frameCheckBox.setGeometry(QRect(230, 310, 78, 20))
        self.frameCheckBox.setFont(font)
        self.transparentCheckBox = QCheckBox(self.centralwidget)
        self.transparentCheckBox.setObjectName(u"transparentCheckBox")
        self.transparentCheckBox.setGeometry(QRect(230, 340, 111, 20))
        self.transparentCheckBox.setFont(font)
        self.alwaysOnTopCheckBox = QCheckBox(self.centralwidget)
        self.alwaysOnTopCheckBox.setObjectName(u"alwaysOnTopCheckBox")
        self.alwaysOnTopCheckBox.setGeometry(QRect(420, 310, 131, 20))
        self.alwaysOnTopCheckBox.setFont(font)
        self.clickThroughCheckBox = QCheckBox(self.centralwidget)
        self.clickThroughCheckBox.setObjectName(u"clickThroughCheckBox")
        self.clickThroughCheckBox.setGeometry(QRect(420, 340, 121, 20))
        self.clickThroughCheckBox.setFont(font)
        self.deleteBtn = QPushButton(self.centralwidget)
        self.deleteBtn.setObjectName(u"deleteBtn")
        self.deleteBtn.setGeometry(QRect(230, 530, 101, 24))
        self.enabledCheckBox = QCheckBox(self.centralwidget)
        self.enabledCheckBox.setObjectName(u"enabledCheckBox")
        self.enabledCheckBox.setGeometry(QRect(500, 530, 91, 20))
        self.enabledCheckBox.setFont(font)
        self.cropLeftInput = QSpinBox(self.centralwidget)
        self.cropLeftInput.setObjectName(u"cropLeftInput")
        self.cropLeftInput.setGeometry(QRect(330, 240, 81, 24))
        self.cropTopInput = QSpinBox(self.centralwidget)
        self.cropTopInput.setObjectName(u"cropTopInput")
        self.cropTopInput.setGeometry(QRect(330, 210, 81, 24))
        self.listView = QListView(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(10, 20, 201, 531))
        self.listView.setFont(font)
        self.newPageBtn = QPushButton(self.centralwidget)
        self.newPageBtn.setObjectName(u"newPageBtn")
        self.newPageBtn.setGeometry(QRect(230, 500, 101, 24))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"URL", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Crop Top", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Crop Bottom", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Crop Left", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Crop Right", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Opacity", None))
        self.frameCheckBox.setText(QCoreApplication.translate("MainWindow", u"Frame", None))
        self.transparentCheckBox.setText(QCoreApplication.translate("MainWindow", u"Transparent", None))
        self.alwaysOnTopCheckBox.setText(QCoreApplication.translate("MainWindow", u"Always On Top", None))
        self.clickThroughCheckBox.setText(QCoreApplication.translate("MainWindow", u"Click Through", None))
        self.deleteBtn.setText(QCoreApplication.translate("MainWindow", u"Delete Window", None))
        self.enabledCheckBox.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.newPageBtn.setText(QCoreApplication.translate("MainWindow", u"New Window", None))
    # retranslateUi

